spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
          connect-timeout: 10000
          response-timeout: 7s
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/order/**
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notification/**
resilience4j:
  time limiter:
    configs:
      default:
        timeoutDuration: 7000
        cancelRunningFuture: true